### ISSUE TITLE
jquery is missing as dependency

### ISSUE THREAD

**Issue by markshust** [okgrow/router-autoscroll#29] opened 2016-01-05 20:20 UTC

**Comment by pauldowman** [comment] 2016-01-05 20:56
I think this is by design. A lot of people don't want jquery so we shouldn't pull it in. If you're using it then it should use it (for `animate()` etc.), but if not then it should still work and not pull jquery in as a surprise.

See [here](https://github.com/okgrow/router-autoscroll/blob/master/client/router-autoscroll.js#L13-L15), then look for the places where we do `if (_jQuery)...`

**Comment by pauldowman** [comment] 2016-01-05 20:57
Closing, assuming there are no issues if you have jquery already.

**Closed as completed by pauldowman** 2016-01-05 20:57 UTC
Labels: wontfix

**Comment by markshust** [comment] 2016-01-05 21:32
This jquery checker functionality doesn't work then. I receive the following error when jquery isn't installed in meteor:

![screen shot 2016-01-05 at 4 31 28 pm](https://cloud.githubusercontent.com/assets/437029/12128206/da24ec28-b3c9-11e5-8c98-fdd6237f3721.png)

Is there a reason to use jquery at all? If so, what's the reasoning?

**Comment by markshust** [comment] 2016-01-05 21:36
Ignore the above, I was obviously on an older version :| 

That said, still wondering why jquery-specific functionality is there at all. Seems to work the same without it.

**Comment by benthemonkey** [comment] 2016-01-05 21:39
jquery provides more robust cross-browser support and the scroll animation (which could be implemented without jquery, but not easily in a way that supports all browsers)

**Comment by markshust** [comment] 2016-01-05 21:56
Ok thanks -- I was getting a scrolling animation, but I could see how that could be browser-specific. Thanks!
